MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 5
DATASETS:
  TRAIN: ("kitti_train", )
  #TEST: ("kitti_test",)
  TEST: ("kitti_train",)

INPUT:
  MIN_SIZE_TRAIN: (384,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 384
  MAX_SIZE_TEST: 1280
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
  WARMUP_METHOD: "linear"

OUTPUT_DIR: "output"
